name: MLOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install dvc[s3] pandas scikit-learn joblib

      - name: Pull dataset from DVC remote
        run: dvc pull

      - name: Run training pipeline
        run: dvc repro